# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

atom:
  dt: 0.002 # 0.002 0.005
  decimation: 10 # 10  4
  fixed_kp: [430.24, 278.81, 144.89, 320.80, 60.64, 60.64,  # 左腿6（禁用PD控制）
          430.24, 278.81, 144.89, 320.80, 60.64, 60.64, 
          320,  # 腰1
          80, 80, 80, 60, 60, 80, 80,  # 左臂7
          80, 80, 80, 60, 60, 80, 80]
  fixed_kd: [27.39, 17.75, 9.22, 20.42, 3.86, 3.86,  # 左腿6（禁用PD控制）
          27.39, 17.75, 9.22, 20.42, 3.86, 3.86,  # 右腿6（禁用PD控制）
          32.0,  # 腰1
          2, 2, 2, 0.5, 0.5, 0.5, 0.5,  # 左臂7
          2, 2, 2, 0.5, 0.5, 0.5, 0.5]
  num_of_dofs: 27
  torque_limits: [280.0, 308.0, 140.0, 360.0, 130.0, 130.0,
                  280.0, 308.0, 140.0, 360.0, 130.0, 130.0,
                  250.0,
                  56.0, 36.0, 36.0, 36.0, 18.6, 18.6, 18.6,
                  56.0, 36.0, 36.0, 36.0, 18.6, 18.6, 18.6]
  # default_dof_pos: [-0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
  #                   -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
  #                   0.0, 
  #                   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  #                   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  #                   0.0, 0.0
  #                   ]
  default_dof_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
                    0.0, 
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  dof_pos_lower_limits: [
      # 左腿 6
      -2.5656, -0.2618, -2.7925,  0.0000, -0.8727, -0.4800,
      # 右腿 6
      -2.5656, -1.6581, -2.7925,  0.0000, -0.8727, -0.4800,
      # 腰 1
      -2.7925,
      # 左臂 7
      -2.97, -0.43, -2.97, -1.57, -2.97, -1.57, -1.57,
      # 右臂 7
      -2.97, -3.14, -2.97, -1.57, -2.97, -1.57, -1.57
  ]
  dof_pos_upper_limits: [
      # 左腿 6
      3.0194,  1.6581,  2.7925,  2.4871,  0.5236,  0.4800,
      # 右腿 6
      3.0194,  0.2618,  2.7925,  2.4871,  0.5236,  0.4800,
      # 腰 1
      2.7925,
      # 左臂 7
      2.97,  3.14,  2.97,  2.00,  2.97,  1.57,  1.57,
      # 右臂 7
      2.97,  0.43,  2.97,  2.00,  2.97,  1.57,  1.57
  ]
  joint_names: [left_hip_pitch_joint, left_hip_roll_joint, left_hip_yaw_joint, left_knee_joint, left_ankle_pitch_joint, left_ankle_roll_joint,
                right_hip_pitch_joint, right_hip_roll_joint, right_hip_yaw_joint, right_knee_joint, right_ankle_pitch_joint, right_ankle_roll_joint,
                waist_yaw_joint, 
                left_shoulder_pitch_joint, left_shoulder_roll_joint, left_shoulder_yaw_joint, left_elbow_pitch_joint, left_elbow_roll_joint, left_wrist_pitch_joint, left_wrist_yaw_joint,
                right_shoulder_pitch_joint, right_shoulder_roll_joint, right_shoulder_yaw_joint, right_elbow_pitch_joint, right_elbow_roll_joint, right_wrist_pitch_joint, right_wrist_yaw_joint]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
